# Generated by Django 3.1.3 on 2020-11-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
