# Generated by Django 3.1.3 on 2020-11-28 04:13

import apps.sliders.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('btn_text', models.CharField(max_length=50, verbose_name='Button text')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='Link')),
                ('image', models.ImageField(upload_to=apps.sliders.models.slider_image_directory_path, verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='sliders.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['order'],
            },
        ),
    ]
