# Generated by Django 3.1.3 on 2020-11-28 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_auto_20201128_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='category',
            new_name='group',
        ),
    ]
